site_name: jsonmask
site_description: Implements Google Partial Response / json-mask in Python
site_author: Craig Labenz
repo_url: https://github.com/zapier/jsonmask

theme: readthedocs

pages:
- Home: index.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
